spring.application.name=peerislands-assignment

management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=Peerislands Assignment
info.app.description=Order Management API
info.app.version=0.0.1-SNAPSHOT
